CREATE TABLE "addresses" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "street_address" varchar NOT NULL,
  "apartment_suite" varchar,
  "city" varchar NOT NULL,
  "state_province" varchar,
  "postal_code" varchar,
  "country" varchar NOT NULL,
  "latitude" decimal,
  "longitude" decimal,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "meters" (
  "meter_identifier" varchar PRIMARY KEY,
  "connection_type" varchar NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date,
  "address_id" int NOT NULL
);

CREATE TABLE "usage_entries" (
  "usage_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meter_identifier" varchar NOT NULL,
  "time" TIMESTAMPTZ NOT NULL,
  "reading_time_type" varchar,
  "reading_subtype" varchar,
  "value" decimal,
  "cumulative_reading" decimal,
  "temperature" decimal
);

COMMENT ON COLUMN "addresses"."latitude" IS 'Decimal degrees for geolocation';

COMMENT ON COLUMN "addresses"."longitude" IS 'Decimal degrees for geolocation';

COMMENT ON COLUMN "usage_entries"."reading_time_type" IS 'low or high for electricity';

COMMENT ON COLUMN "usage_entries"."reading_subtype" IS 'Subtype: e.g., delivery or return)';

COMMENT ON COLUMN "usage_entries"."value" IS 'Value of the specific reading (e.g., 0.78)';

COMMENT ON COLUMN "usage_entries"."cumulative_reading" IS 'Cumulative reading (e.g., 16,196.41), nullable';

COMMENT ON COLUMN "usage_entries"."temperature" IS 'Temperature in Celsius at the time of the reading, nullable';

ALTER TABLE "meters" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("address_id");

ALTER TABLE "usage_entries" ADD FOREIGN KEY ("meter_identifier") REFERENCES "meters" ("meter_identifier");
